### ISSUE TITLE
double register on dataset

### ISSUE THREAD

**Issue by myf** [SEL-Columbia/bamboo-meteor-client#11]
It seems to be that when two clients connected the server and requesting th same datasetURL at the same time, the dataset is registered twice. instead of "grade sex income name" it shows "grade sex income name grade sex income name"

**Comment by myf** [comment]
# confirmed

when two client instances register the dataset at the same time it is registered twice.

Things to consider:
- js async, the setTimeout 1 sec might complicate things
- blocking: when client 1 query the dataset, client two should be waiting
- use bambooid isntead of url to identify

**Comment by myf** [comment]
Datasets collection is working just fine. There are some conflicts of reading and writing to mongo in the same Fiber. will observe and waiting for testing suites.

**Comment by pld** [comment]
when two users upload the same dataset they should get two separate datasets
