### ISSUE TITLE
Don't show group by for rows with all unique entries

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo-meteor-client#13]

**Comment by nanzhuwang** [comment]
Here is an example about LGA.
What if every lga is different, but people still want to see the graphs grouped by lga? 

Another example,
What if we have 100 names and 2 of them are different? In this case, we can't define "useless" or "useful" by "rows with all unique entries".

We may filter some useless "group by button" based on the data analysis.

**Comment by myf** [comment]
the existing behavior in bamboo is that if it's numerical it marks it to be noncategorical. what if there's grades of 1,2,3 and 4 and people want to see the groups.

**Comment by myf** [comment]
we can also remind people howmany graphs they are generation by their action. so hopefully when they see 622 graphs are being generated they will not generate it.

**Comment by nanzhuwang** [comment]
If 622 graphs are generated, it usually means that the "group-by button" they click may not be a category. We may give the users the freedom to choose what they like.

**Comment by pld** [comment]
Good points, let not worry about this for now, added to a new issue, https://github.com/modilabs/bamboo-meteor-client/issues/20, edit as appropriate

**Comment by myf** [comment]
see #20
