### ISSUE TITLE
Show introduction text box on top of page

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo-meteor-client#16]
write functionality with, don't worry about the copy we can fill it in later

**Comment by myf** [comment]
![image1](http://i.imgur.com/VM3TV.png)
![image2](http://i.imgur.com/ylCp0.png)
![image3](http://i.imgur.com/UzAni.png)
![image4](http://i.imgur.com/4T3x9.png)

**Comment by myf** [comment]
done
