### ISSUE TITLE
better insertion

### ISSUE THREAD

**Issue by myf** [SEL-Columbia/bamboo-meteor-client#23]
the problem with inserting large dataset into meteor's minimongo backend struction takes too long. We can insert them as a block instead of one by one. or we can trash the insertion mechanism.

**Comment by pld** [comment]
I say do not cache, no need to worry about the nuances of mongo storage when the service handles that

**Comment by nanzhuwang** [comment]
the publish/subscribe is implemented. in this way, a client may only read what he submits. it is also a good news for the speed problem. the speed may increase.

**Comment by myf** [comment]
close for now. will look at it later when bamboo update finishes. it works pretty well for now.
