### ISSUE TITLE
url design

### ISSUE THREAD

**Issue by myf** [SEL-Columbia/bamboo-meteor-client#32]
after Session(currentDatasetURL) is defined, we should go to http://[hostname]/[session-url] something like that so that it is retrievable.

**Comment by myf** [comment]
note to self: should ask dorey and prajwol

**Comment by nanzhuwang** [comment]
problem is partly soved.
now if we have the url like : worldtalks.org:3000/#/"the csv url address", the website may directly router to read the csv file. next, we may implement the url hook. it is like the website will also router to the worldtalks.org:3000/#/"the csv url address" after the submit button is clicked.
