### ISSUE TITLE
Add titles and labels for plots

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo-meteor-client#33]
- have title for each plot that is made (either in the plot or in HTML near it, whatever's easier)
- have labels for the axes

**Comment by nanzhuwang** [comment]
what kind of titles? do you like the current title and category after charting?

**Comment by pld** [comment]
for example for the box plot of grade:
- title is "Box plot of grade"
- Y-axis is grade

for a bar of sex:
- title is "Bar chart of sex"
- Y-axis label is count or amount

**Comment by myf** [comment]
what about y-axis as sex, jk
