### ISSUE TITLE
error handling!

### ISSUE THREAD

**Issue by myf** [SEL-Columbia/bamboo-meteor-client#39]
when bamboo spits out junk we should tell users this is not our fault but either bamboo server or your dataset is broken.

**Comment by nanzhuwang** [comment]
basically, we need to handle three types of errors on the client side. 
1. the errors from the server side, like bamboo server returns the obj {"error" : "...."} or bamboo is down.
2. error report about request/receive, like 500 Internal Server Error. 
3. errors from the meteor or the client side, like function ToLowerCase problem in http.js or meteor crashes...

**Comment by nanzhuwang** [comment]
could peter or mark give us the error list that bamboo uses when processing error?

**Comment by myf** [comment]
making progress. Server Side insertion errors are identified and i was on the path of sending the message to the front end. Then I discovered Meteor.publish/Meteor.subscribe which makes a lot more sense than autopublish. It can probably solve the large database problem as well
