### ISSUE TITLE
Pull schema from bamboo

### ISSUE THREAD

**Issue by prabhasp** [SEL-Columbia/bamboo-meteor-client#5]
and replace the "slugs" (= names in form-json lingo) with prettier names (= labels in form-json lingo).
dependency: https://github.com/modilabs/bamboo/issues/77

**Comment by myf** [comment]
is this still relevant now that bamboo is changed?

**Comment by prabhasp** [comment]
yes.

On Thu, Jun 14, 2012 at 4:55 PM, Myf Ma <
reply@reply.github.com

> wrote:
> 
> is this still relevant now that bamboo is changed?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/modilabs/bamboo-meteor-client/issues/5#issuecomment-6340344

## 

Prabhas Pokharel
http://twitter.com/prabhasp
Nepal mobile: +977 98137 91044
US mobile: +1 347 948 7654
skype/facebook/whatever: prabhasp

**Comment by myf** [comment]
ok, just talked to pld. He said the schema is going to be there in the next couple of days. We are happy to implement

**Comment by myf** [comment]
pulled. close

**Comment by myf** [comment]
pulled. close.
