### ISSUE TITLE
persistence for the user habits

### ISSUE THREAD

**Issue by nanzhuwang** [SEL-Columbia/bamboo-meteor-client#56]
do it by “referral_url”; formhub should pass https://formhub.org/USERNAME to the js-client

**Comment by nanzhuwang** [comment]
The user persistency means the previous charts generated by the users can be retrieved. Since currently we have to data structure at the backend to store the user information or user habit, we are going to design the url that contains several parameters like "view field" & "groupable field"

( e.g.: `http://starscream.modilabs.org:8080/#/"view_field=[FIELD NAME]&groupable_field=[GROUP NAME]&url=.../csv_file_url/`),

and the previous charts can be retrieved by those two parameters. And in the future, formhub may store the users chart information and we can use this url design to direct to a certain page with previous charts.

**Comment by nanzhuwang** [comment]
after talking to prabhas, the url design changes. the url only needs two paramesters: referral url(user formhub link) & cvs file url. then a pair of key/value like (referral url + csv file url)-> fields will be stored in the database.  the previous charts can be retrieved by those fields.
in this way, formhub doesn't need to store any extra information. instead, bamboo needs to have a public new data structure to handle that.

**Comment by prabhasp** [comment]
On Thu, Aug 23, 2012 at 4:02 PM, Nanzhu notifications@github.com wrote:

> after talking to prabhas, the url design changes. the url only needs two
> paramesters: referral url(user formhub link) & cvs file url. then a pair of
> key/value like (referral url + csv file url)-> fields will be stored in the
> database. the previous charts can be retrieved by those fields.
> in this way, formhub doesn't need to store any extra information. instead,
> bamboo

not bamboo, bamboo-meteor-client; this will be specific to the (bargraph)
client.

> needs to have a public new data structure to handle that.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/bamboo-meteor-client/issues/56#issuecomment-7982194.

## 

Prabhas Pokharel
http://twitter.com/prabhasp
US mobile: +1 347 948 7654
skype/facebook/whatever: prabhasp

**Comment by pld** [comment]
OK, I believe that's what was understood, for the schema the lighter/simpler/conciser the better.
