### ISSUE TITLE
Figure out how to not overwhelm the user with so many fields

### ISSUE THREAD

**Issue by prabhasp** [SEL-Columbia/bamboo-meteor-client#6]
Most datasets are likely to have many fields; we need to figure out a user-interface that allows the user to narrow down into a few fields so they are not overwhelmed.

**Comment by myf** [comment]
# here's the design after talked to meghana,

user's work flow:
1. first page a ginormous url bar for csv/formhub input, it then zaps up to show :->
2. at the top of the page there are two selection boxes, one for colomns for visible field and another for group_by. The chosenjs (http://harvesthq.github.com/chosen/) might be appropriate here
3. after selelction, the bottom of the page will display dem charts in boxes

# 

![flowchart](http://i.imgur.com/ocNzT.jpg)

**Comment by prabhasp** [comment]
being totally re-designed with alex.
