### ISSUE TITLE
have a bottom-left "powered by bamboo.io graphic" (low priority)

### ISSUE THREAD

**Issue by nanzhuwang** [SEL-Columbia/bamboo-meteor-client#60]

**Comment by nanzhuwang** [comment]
@mkhandekar could you give us a "powered by bamboo.io graphic"? Thx.

**Comment by mkhandekar** [comment]
The solution is to have a "Powered by Bamboo.io" tag at the bottom right with a white background (no border) so it is as inconspicuous as possible, but persistent throughout your viewing experience.
