### ISSUE TITLE
implement the new design

### ISSUE THREAD

**Issue by nanzhuwang** [SEL-Columbia/bamboo-meteor-client#65]
implement roger's new design, including:
introduction section
download/close buttons in graph areas

**Comment by prabhasp** [comment]
is there a picture that you can upload somewhere? would like to have a look.

**Comment by myf** [comment]
![img1](http://i.imgur.com/8r4USh.jpg)
![img2](http://i.imgur.com/tjpAYh.jpg)
![img3](http://i.imgur.com/W7jNnh.jpg)
