### ISSUE TITLE
meteor-client running in a production evironment

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo-meteor-client#71]
Some options,
1. we keep it on starscream and pretend it's a production environment
2. we tack it onto an existing EC2 server, like the formhub production server (or one of the linodes but I don't know their status)
3. we have a new EC2 instance, probably a tiny or small that only runs the client

The list is ordered by increasing time-to-setup and stability.  I suggest we go with (1) for now then next week see if others have input and probably switch to (3).

**Comment by myf** [comment]
it's on starscream now. in formhub settings there's a METEORURL declaration we can mess with once we get EC2

**Comment by pld** [comment]
we're putting it on the bamboo EC2 server, it's close needs subdomain and nginx config cleanup

**Comment by pld** [comment]
http://charts.bamboo.io/
