### ISSUE TITLE
check to see if data is suitable for charting

### ISSUE THREAD

**Issue by myf** [SEL-Columbia/bamboo-meteor-client#8]
some columns have no data, some has too much. what is the best way to kick them out?

**Comment by prabhasp** [comment]
two filters:
- type: "select one" in form.json - kicks out the 'too many'
- only one field, and its "n/a" - kicks out the irrelevant / too few.

On Thu, Jun 7, 2012 at 3:04 PM, Myf Ma <
reply@reply.github.com

> wrote:
> 
> some columns have no data, some has too much. what is the best way to kick
> them out?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/modilabs/bamboo-meteor-client/issues/8

## 

Prabhas Pokharel
http://twitter.com/prabhasp
Nepal mobile: +977 98137 91044
US mobile: +1 347 948 7654
skype/facebook/whatever: prabhasp

**Comment by myf** [comment]
that sounds good

**Comment by myf** [comment]
also people do not want to group_by name. that does'nt make sense. what does it mean by "that doesn't make sense" to a computer. 
1. if every field is its own groupval, that sucks
2. ..........

**Comment by nanzhuwang** [comment]
The graphs grouped by name cannot be shown in the page. After checking, it is found that 1. we have huge info about name, and 2. the information grouped by name is inserted in summaries correctly. We assume that the problem is because of "overflow".

**Comment by prabhasp** [comment]
this is a **future** feature. once bamboo implements https://github.com/modilabs/bamboo/issues/77, any field that is a `string` should be a group-by-enabled.
the schema that bamboo is planning to implement is [the sdf schema](http://www.dataprotocols.org/en/latest/simple-data-format.html).. after that implementation is complete, the `olap_type` field will determine whether something is groupable... anything with either `measure` or `dimension` as an `olap_type` is groupable.
however, having that support on bamboo for formhub datasets will take quite a while.

**Comment by pld** [comment]
https://github.com/modilabs/bamboo-meteor-client/issues/13
