### ISSUE TITLE
error handling: catch TypeError

### ISSUE THREAD

**Issue by myf** [SEL-Columbia/bamboo-meteor-client#9]
I have no error handling at all. recently there have been many 500s from bamboo.io during group_by and i should capture them and either ignore or display error messages.

**Comment by myf** [comment]
so some of these problems are not caused by bamboo,

# quote:

http.js:118
      parser.incoming._addHeaderLine(k.toLowerCase(), v);
                                       ^
TypeError: Cannot call method 'toLowerCase' of undefined
    at HTTPParser.parserOnMessageComplete [as onMessageComplete](http.js:118:40)
    at Socket.ondata (http.js:1468:22)

#     at TCP.onread (net.js:374:27)

it seems that some of these variable is not carried over to the http.js

**Comment by myf** [comment]
toLowerCase issue is not really recontructable and according to http://stackoverflow.com/questions/7334481/uncaught-typeerror-cannot-call-method-tolowercase-of-undefined it may have been a jQuery problem that only appears in local testing

**Comment by pld** [comment]
wrap that in a try catch block for now
